Format all supported files with prettier + eslint. (#510)
* Format all supported files with prettier + eslint.

* Run lint on CI too.

* Better document package-lock.json linting.

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -41,7 +41,6 @@ jobs:
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}
-      # - run: curl -sL https://firebase.tools | bash
       - run: npm ci
       - name: Run tests against emulator
         # forceExit: something is not cleaning up - likely firebase-app that needs to be deleted, investigate
@@ -51,7 +50,7 @@ jobs:
         env:
           CI: true
 
-  check-package-lock:
+  lint:
     runs-on: ubuntu-latest
 
     strategy:
@@ -64,5 +63,10 @@ jobs:
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}
-      - run: npm install --package-lock-only
-      - run: "git diff --exit-code -- package-lock.json || (echo 'Error: package-lock.json is changed during npm install! Please make sure to use npm >= 6.9.0 and commit package-lock.json.' && false)"
+      # Use `npm install` which fixes package-lock.json in place if it is not
+      # already matching package.json. The resulting diff is caught below.
+      - run: npm install # Not using `npm ci`, which won't touch lock files.
+      - name: Lint package-lock.json
+        run: "git diff --exit-code -- package-lock.json || (echo 'Error: package-lock.json is changed during npm install! Please make sure to use npm >= 6.9.0 and commit package-lock.json.' && false)"
+      - name: Lint source files
+        run: npm run lint
